SaleManagement.Protal/Controllers/NoticeController.cs
using Dickson.Web.Mvc.ModelBinding;
using SaleManagement.Core.Models;
using SaleManagement.Core.ViewModel;
using SaleManagement.Managers;
using SaleManagement.Protal.Web;
using System;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace SaleManagement.Protal.Controllers
{
    public class NoticeController : PortalController
    {
        [PagingParameterInspector]
        public async Task<ActionResult> List(PagingRequest request)
        {
            if (!Request.IsAjaxRequest())
                return View();

            var manager = new NoticeManager(User);
            var paging = await manager.GetNoticesAsync(request.Start, request.Take);

            return Json(true, string.Empty, new
            {
                paging.Total,
                List = paging.List,
            });
        }

        public async Task<ActionResult> Edit(int id = 0)
        {
            var manager = new NoticeManager(User);
            var notice = new Notice();
            if (id > 0)
            {
                notice = await manager.GetNoticeAsync(id);
            }

            return View(notice);
        }

        [HttpPost]
        public async Task<JsonResult> Edit(Notice notice)
        {
            if (!ModelState.IsValid)
                return Json(false, data: ErrorToDictionary());

            var manager = new NoticeManager(User);
            var result = await manager.SaveNotice(notice);

            return Json(result);
        }

        [HttpPost]
        public async Task<JsonResult> Delete(int id)
        {
            if (id <= 0)
                throw new ArgumentOutOfRangeException(nameof(id));

            var manager = new NoticeManager(User);
            var result = await manager.DeleteNoticeAsync(id);

            return Json(result);
        }
    }
}

SaleManagement.Protal/Views/Notice/Edit.cshtml
@model SaleManagement.Core.Models.Notice
@{
    Layout = null;
}

@using (Html.BeginForm("Edit", "Notice", FormMethod.Post, new { id = "editNoticeForm" }))
{
    @Html.HiddenFor(model => model.Id)
    <div class="form-horizontal">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">×</button>
            <h4 class="modal-title">新增/编辑公告</h4>
        </div>
        <div class="modal-body">
            <div class="form-group">
                <label class="control-label col-md-2" for="Name">
                    <span class="text-danger">*</span>内容
                </label>
                <div class="col-md-8">
                    @Html.TextAreaFor(model => model.Content,  new { @class = "form-control",rows = "5", })
                    @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <a href="#" class="btn btn-default" data-dismiss="modal">关闭</a>
            <input class="btn btn-primary" type="submit" value="保存" />
        </div>
    </div>
}

@Scripts.Render("~/bundles/js/jqueryval")
@Scripts.Render("~/bundles/js/ajaxForm")
@Scripts.Render("~/bundles/js/notice/edit")

SaleManagement.Protal/Views/Notice/List.cshtml
@{
    Title("公告管理");
}

<div>
    <ul class="breadcrumb">
        <li>
            <a href="/home/index">首页</a>
        </li>
        <li>
            <a href="/notice/list">公告管理</a>
        </li>
    </ul>
</div>

<div class="row">
    <div class="box col-md-12">
        <div class="box-inner">
            <div class="box-header well" data-original-title="">
                <h2>公告列表</h2>
                <div class="box-icon">
                    <a href="/Notice/Edit" data-toggle="modal" data-target="#modal" class="btn">
                        <i class="glyphicon glyphicon-plus"></i>
                        新增
                    </a>
                </div>
            </div>
            <div class="box-content">
                <table class="table table-striped table-bordered bootstrap-datatable  responsive">
                    <thead>
                        <tr>
                            <th class="col-md-8">内容</th>
                            <th>创建日期</th>
                            <th>操作</th>
                        </tr>
                    </thead>
                    <tbody data-bind="foreach:notices">
                        <tr>
                            <td data-bind="text:content"></td>
                            <td data-bind="text:formatDate(created)"></td>
                            <td>
                                <a class="btn btn-danger btn-sm" data-bind="click:$parent.deleteClick">删除</a>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="text-center"><ul id="noticeListPage"></ul></div>
        </div>
    </div>
    <!--/span-->
</div><!--/row-->

<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
     aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">

        </div>
    </div>
</div>
@section scripts{
    @Scripts.Render("~/bundles/js/knockout")
    @Scripts.Render("~/bundles/js/pager")
    @Scripts.Render("~/bundles/js/notice/list")
}