SaleManagement.Protal/Models/DailyGoldPrice/DailyGoldPriceViewModel.cs
using SaleManagement.Core.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SaleManagement.Protal.Models.DailyGoldPrice
{
    public class DailyGoldPriceViewModel
    {
        public DailyGoldPriceViewModel()
        {
            Date = DateTime.Now.ToString("yyyy-MM-dd");
        }

        public DailyGoldPriceViewModel(Core.Models.DailyGoldPrice dailyGoldPrice)
        {
            Id = dailyGoldPrice.Id;
            ColorFormId = dailyGoldPrice.ColorForm.Id;
            ColorFormName = dailyGoldPrice.ColorForm.Name;
            Date = dailyGoldPrice.Date.ToString("yyyy-MM-dd"); ;
            Price = dailyGoldPrice.Price;
        }

        public int Id { get; set; }

        [Display(Name = "成色")]
        [Required(ErrorMessage = "请选择{0}")]
        public int ColorFormId { get; set; }

        public string ColorFormName { get; set; }

        [Display(Name ="日期")]
        [Required(ErrorMessage ="请填写{0}")]
        public string Date { get; set; }

        public double Price { get; set; }

        public IEnumerable<ColorForm> ColorForms { get; set; }
    }
}

SaleManagement.Protal/Controllers/DailyGoldPriceController.cs
using Dickson.Web.Mvc.ModelBinding;
using SaleManagement.Core;
using SaleManagement.Core.Models;
using SaleManagement.Core.ViewModel;
using SaleManagement.Managers;
using SaleManagement.Protal.Models.DailyGoldPrice;
using SaleManagement.Protal.Web;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace SaleManagement.Protal.Controllers
{
    public class DailyGoldPriceController : PortalController
    {
        [PagingParameterInspector]
        public async Task<ActionResult> List(PagingRequest request)
        {
            if (!Request.IsAjaxRequest())
                return View();

            var manager = new DailyGoldPriceManager(User);
            var paging = await manager.GetDailyGoldPrices(request.Start, request.Take);

            var users = paging.List.Select(u =>
                new DailyGoldPriceViewModel(u));

            return Json(true, string.Empty, new
            {
                paging.Total,
                List = users,
            });
        }

        public async Task<ActionResult> Edit(int id = 0)
        {
            var manager = new DailyGoldPriceManager(User);
            var dailyGoldPriceViewModel = new DailyGoldPriceViewModel();

            if (id > 0)
            {
                var dailyGoldPrice = await manager.GetDailyGoldPriceAsync(id);
                if (dailyGoldPrice != null)
                {
                    dailyGoldPriceViewModel = new DailyGoldPriceViewModel(dailyGoldPrice);
                }
            }

            var colorFormManager = new BasicDataManager(User);
            dailyGoldPriceViewModel.ColorForms = await colorFormManager.GetColorFormsAsync();

            return View(dailyGoldPriceViewModel);
        }

        [HttpPost]
        public async Task<JsonResult> Edit(DailyGoldPriceViewModel viewModel)
        {
            if (!ModelState.IsValid)
                return Json(false, data: ErrorToDictionary());

            var dailyGoldPrice = new DailyGoldPrice()
            {
                Id = viewModel.Id,
                ColorFormId = viewModel.ColorFormId,
                CompanyId = User.CompanyId,
                CreatorId = User.Id,
                Price = viewModel.Price,
                Date = Convert.ToDateTime(viewModel.Date)
            };
            var manager = new DailyGoldPriceManager(User);
            var result = await manager.SaveDailyGoldPrice(dailyGoldPrice);

            return Json(result);
        }

        [HttpPost]
        public async Task<JsonResult> Delete(int id)
        {
            if (id <= 0)
                throw new ArgumentOutOfRangeException(nameof(id));

            var manager = new DailyGoldPriceManager(User);
            var result = await manager.DeleteDailyGoldPriceAsync(id);

            return Json(result);
        }

        public async Task<ActionResult> Add()
        {
            var colorFormManager = new BasicDataManager(User);
            var colorForms = await colorFormManager.GetColorFormsAsync();
            var dailyGoldPriceViewModels = colorForms.Select(c =>
            {
                return new DailyGoldPriceViewModel
                {
                    ColorFormId = c.Id,
                    ColorFormName = c.Name
                };
            });
            return View(dailyGoldPriceViewModels);
        }

        [HttpPost]
        public async Task<JsonResult> Add(IEnumerable<DailyGoldPriceViewModel> dailyGoldPriceViewModels)
        {
            if (!ModelState.IsValid)
                return Json(false, data: ErrorToDictionary());

            var dailyGoldPrices = dailyGoldPriceViewModels.Select(r =>
            {
                return new DailyGoldPrice
                {
                    ColorFormId = r.ColorFormId,
                    CompanyId = User.CompanyId,
                    Date = Convert.ToDateTime(r.Date),
                    Price = r.Price,
                    CreatorId = User.Id
                };
            });
            var manager = new DailyGoldPriceManager(User);
            var result = await manager.SaveDailyGoldPrices(dailyGoldPrices);

            return Json(true);
        }
    }
}

SaleManagement.Protal/Views/DailyGoldPrice/Add.cshtml
@model IEnumerable<SaleManagement.Protal.Models.DailyGoldPrice.DailyGoldPriceViewModel>
@{
    Layout = null;
}

@Styles.Render("~/Bundles/Static/Css/DateTimePicker")

@using (Html.BeginForm("Add", "DailyGoldPrice", FormMethod.Post, new { id = "addDailyGoldPriceForm" }))
{
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">×</button>
        <h4 class="modal-title">新增/编辑每日金价</h4>
    </div>
    <div class="modal-body">
        <table class="table table-striped table-bordered bootstrap-datatable  responsive">
            <thead>
                <tr>
                    <th>日期</th>
                    <th>成色</th>
                    <th>价格</th>
                </tr>
            </thead>
            <tbody id="tbody">
                @{
                    var index = 0;
                    foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.Date</td>
                            <td>@item.ColorFormName</td>
                            <td>
                                <input type="hidden" name="dailyGoldPriceViewModels[@index].Date" value="@item.Date" />
                                <input type="hidden" name="dailyGoldPriceViewModels[@index].ColorFormId" value="@item.ColorFormId" />
                                <input type="text" name="dailyGoldPriceViewModels[@index].Price" autocomplete="off" />
                            </td>
                        </tr>
                        index++;
                    }
                }
            </tbody>
        </table>
    </div>
    <div class="modal-footer">
        <a href="#" class="btn btn-default" data-dismiss="modal">关闭</a>
        <input class="btn btn-primary" type="submit" value="保存" />
    </div>
                    }
@Scripts.Render("~/bundles/js/dateTimePicker")
@Scripts.Render("~/bundles/js/jqueryval")
@Scripts.Render("~/bundles/js/ajaxForm")
@Scripts.Render("~/bundles/js/dailyGoldPrice/add")

SaleManagement.Protal/Views/DailyGoldPrice/Edit.cshtml
@model SaleManagement.Protal.Models.DailyGoldPrice.DailyGoldPriceViewModel
@{
    Layout = null;
}

@Styles.Render("~/Bundles/Static/Css/DateTimePicker")

@using (Html.BeginForm("Edit", "DailyGoldPrice", FormMethod.Post, new { id = "editDailyGoldPriceForm" }))
{
    @Html.HiddenFor(model => model.Id)
    <div class="form-horizontal">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">×</button>
            <h4 class="modal-title">新增/编辑每日金价</h4>
        </div>
        <div class="modal-body">
            <div class="form-group">
                <label class="control-label col-md-2" for="Name">
                    <span class="text-danger">*</span>成色
                </label>
                <div class="col-md-6">
                    @{
                        var colorForms = Model.ColorForms.Select(c => new SelectListItem
                        {
                            Value = c.Id.ToString(),
                            Text = c.Name
                        });
                    }
                    @Html.DropDownListFor(model => model.ColorFormId, colorForms, "请选择", new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.ColorFormId, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2" for="Date">
                    <span class="text-danger">*</span>日期
                </label>
                <div class="col-md-6">
                    @Html.TextBoxFor(model => model.Date, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Date, "", new {@class = "text-danger"})
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2" for="Price">
                    <span class="text-danger">*</span>金价
                </label>
                <div class="col-md-6">
                    @Html.TextBoxFor(model => model.Price, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <a href="#" class="btn btn-default" data-dismiss="modal">关闭</a>
            <input class="btn btn-primary" type="submit" value="保存" />
        </div>
    </div>
}
@Scripts.Render("~/bundles/js/dateTimePicker")
@Scripts.Render("~/bundles/js/jqueryval")
@Scripts.Render("~/bundles/js/ajaxForm")
@Scripts.Render("~/bundles/js/dailyGoldPrice/edit")

SaleManagement.Protal/Views/DailyGoldPrice/List.cshtml
@{
    Title("金价管理");
}

<div>
    <ul class="breadcrumb">
        <li>
            <a href="/home/index">首页</a>
        </li>
        <li>
            <a href="/dailyGoldPrice/list">金价管理</a>
        </li>
    </ul>
</div>

<div class="row">
    <div class="box col-md-12">
        <div class="box-inner">
            <div class="box-header well" data-original-title="">
                <h2>每日金价列表</h2>
                <div class="box-icon">
                    <a href="/dailyGoldPrice/Add" data-toggle="modal" data-target="#modal" class="btn">
                        <i class="glyphicon glyphicon-plus"></i>
                        批量新增
                    </a>
                    <a href="/dailyGoldPrice/Edit" data-toggle="modal" data-target="#modal" class="btn">
                        <i class="glyphicon glyphicon-plus"></i>
                        新增
                    </a>
                </div>
            </div>
            <div class="box-content">
                <table class="table table-striped table-bordered bootstrap-datatable  responsive">
                    <thead>
                        <tr>
                            <th>日期</th>
                            <th>成色</th>
                            <th>价格</th>
                            <th>操作</th>
                        </tr>
                    </thead>
                    <tbody data-bind="foreach:prices">
                        <tr>
                            <td data-bind="text:date"></td>
                            <td data-bind="text:colorFormName"></td>
                            <td data-bind="text:price"></td>
                            <td>
                                <a class="btn btn-danger btn-sm" data-bind="click:$parent.deleteClick">删除</a>
                                <a class="btn btn-primary btn-sm" data-bind="click:$parent.editClick">修改</a>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="text-center"><ul id="dailyGoldPriceListPage"></ul></div>
        </div>
    </div>
    <!--/span-->
</div><!--/row-->

<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
     aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">

        </div>
    </div>
</div>
@section scripts{
    @Scripts.Render("~/bundles/js/knockout")
    @Scripts.Render("~/bundles/js/pager")
    @Scripts.Render("~/bundles/js/dailyGoldPrice/list")
}