SaleManagement.Protal/Models/SpotGoodsPattern/SpotGoodPatternPageRequest.cs
using SaleManagement.Core.Models;
using SaleManagement.Core.ViewModel;
using System;
using System.Data.Entity;
using System.Linq;

namespace SaleManagement.Protal.Models.SpotGoodsPattern
{
    public class SpotGoodPatternPageRequest : PagingRequest
    {
        public string SpotGoodTypeId { get; set; }

        public Func<IQueryable<Core.Models.SpotGoodsPattern>, IQueryable<Core.Models.SpotGoodsPattern>> GetSpotGoodsPatternListQueryFilter(SaleUser user)
        {
            Func<IQueryable<Core.Models.SpotGoodsPattern>, IQueryable<Core.Models.SpotGoodsPattern>> filter = query =>
            {

                if (!string.IsNullOrEmpty(SpotGoodTypeId))
                {
                    query = query.Where(f => f.SpotGoodsPatternTypes.Any(t => t.SpotGoodsTypeId == SpotGoodTypeId));
                }


                return query.AsNoTracking();
            };
            return filter;
        }
    }
}

SaleManagement.Protal/Models/SpotGoodsPattern/SpotGoodsPatternEditViewModel.cs
using SaleManagement.Core.Models;
using System.Collections.Generic;

namespace SaleManagement.Protal.Models.SpotGoodsPattern
{
    public class SpotGoodsPatternEditViewModel
    {
        public SpotGoodsPatternEditViewModel()
        {
            SpotGoodsPatternTypeIds = new List<string>();
        }

        public string Id { get; set; }

        public string Name { get; set; }

        public IEnumerable<string> SpotGoodsPatternTypeIds { get; set; }

        public string SpotGoodsPatternTypeIdStr
        {
            get { return string.Join(",", SpotGoodsPatternTypeIds); }
        }

        public string FileInfoId { get; set; }

        public int ProductCategoryId { get; set; }

        public int GemCategoryId { get; set; }


        public double Price { get; set; }

        public string ReferenceData { get; set; }

        public int RowNo { get; set; }

        public List<SpotGoodType> SpotGoodTypes { get; set; }

        public IEnumerable<ProductCategory> ProductCategories { get; set; }

        public IEnumerable<GemCategory> GemCategories { get; set; }
    }
}

SaleManagement.Protal/Models/SpotGoodsPattern/SpotGoodsPatternListItemViewModel.cs
namespace SaleManagement.Protal.Models
{
    public class SpotGoodsPatternListItemViewModel
    {
        public string Id { get; set; }

        public string Name { get; set; }

        public string TypeName { get; set; }

        public string FileInfoId { get; set; }

        public string Url { get; set; }

        public int ProductCategoryId { get; set; }

        public string ProductCategoryName { get; set; }


        public int GemCategoryId { get; set; }

        public string GemCategoryName { get; set; }

        public double Price { get; set; }

        public string ReferenceData { get; set; }
    }
}

SaleManagement.Protal/Models/SpotGoodsPattern/SpotGoodsPatternViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SaleManagement.Protal.Models.SpotGoodsPattern
{
    public class SpotGoodsPatternViewModel
    { 
        public string Id { get; set; }
         
        public string Name { get; set; }
         
        public bool IsDelete { get; set; }
    }
}

SaleManagement.Protal/Controllers/SpotGoodsPatternController.cs
using AutoMapper;
using Dickson.Core.Common.Extensions;
using Dickson.Web.Mvc.ModelBinding;
using SaleManagement.Core;
using SaleManagement.Core.Models;
using SaleManagement.Managers;
using SaleManagement.Protal.Models;
using SaleManagement.Protal.Models.SpotGoodsPattern;
using SaleManagement.Protal.Web;
using System;
using System.Drawing;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace SaleManagement.Protal.Controllers
{
    public class SpotGoodsPatternController : PortalController
    {
        [PagingParameterInspector]
        public async Task<ActionResult> List(SpotGoodPatternPageRequest request)
        {
            if (!Request.IsAjaxRequest())
                return View(request);

            var manager = new SpotGoodsPatternManager(User);
            var paging = await manager.GetSpotGoodsPatternListAsync(request.Start, request.Take, request.GetSpotGoodsPatternListQueryFilter(User));

            return Json(true, string.Empty, new
            {
                paging.Total,
                List = paging.List.Select(r => new SpotGoodsPatternListItemViewModel
                {
                    Id = r.Id,
                    FileInfoId = r.FileInfoId,
                    Name = r.Name,
                    //TypeName = r.SpotGoodType.Name,
                    Price = r.Price,
                    Url = "/Attachment/" + r.FileInfoId + "/Thumbnail"
                })
            });
        }

        public async Task<ActionResult> Add()
        {
            var model = new SpotGoodsPatternEditViewModel();
            var manager = new SpotGoodTypeManager(User);
            model.SpotGoodTypes = await manager.GetSpotGoodTypeListAsync();

            var basicDataManager = new BasicDataManager(User);
            model.ProductCategories = await basicDataManager.GetProductCategoriesAsync();
            model.GemCategories = await basicDataManager.GetGemCategoriesAsync();
            return View(model);
        }

        public async Task<ActionResult> Edit(string Id)
        {
            var manager = new SpotGoodsPatternManager(User);
            var spotGoodsPattern = await manager.GetSpotGoodsPattern(Id);
            var model = Mapper.Map<SpotGoodsPattern, SpotGoodsPatternEditViewModel>(spotGoodsPattern);

            var spotGoodTypeManager = new SpotGoodTypeManager(User);
            model.SpotGoodTypes = await spotGoodTypeManager.GetSpotGoodTypeListAsync();

            var basicDataManager = new BasicDataManager(User);
            model.ProductCategories = await basicDataManager.GetProductCategoriesAsync();
            model.GemCategories = await basicDataManager.GetGemCategoriesAsync();
            model.SpotGoodsPatternTypeIds =
                spotGoodsPattern.SpotGoodsPatternTypes.Select(t => t.SpotGoodsTypeId).ToList();
            return View("Add", model);
        }

        [HttpPost]
        public async Task<ActionResult> Save(SpotGoodsPattern spotGoodsPattern, [NamedModelBinder(typeof(CommaSeparatedModelBinder), "SpotGoodsPatternTypeIdStr")] string[] spotGoodsPatternTypeIdStr)
        {
            if (string.IsNullOrEmpty(spotGoodsPattern.Id))
            {
                spotGoodsPattern.Id = Guid.NewGuid().ToString();
            }
            var manager = new SpotGoodsPatternManager(User);
            var result = await manager.EditSpotGoodsPattern(spotGoodsPattern, spotGoodsPatternTypeIdStr);
            return Json(result);
        }

        [HttpPost]
        public async Task<JsonResult> AddAttachment(AttachmentRequestBase request)
        {
            if (!ModelState.IsValid)
                return Json(false, data: ErrorToDictionary(), contentType: SaleManagentConstants.Misc.JsonResponseContentType);

            Image image = Image.FromStream(request.File.InputStream);

            var file = new Core.Models.FileInfo
            {
                ContentType = request.File.ContentType,
                FileName = request.File.FileName,
                Purpose = FilePurpose.SpotGoodsAttachment.GetDisplayName(),
                Data = await request.File.InputStream.ReadAllBytesAsync(),
                ContentLength = request.File.ContentLength
            };

            string strPhysicsPath = HttpContext.Server.MapPath("~/orderImage");

            file.ThumbnailData =
                ImageHelp.MakeThumbnail(request.File.InputStream, 300, 300, strPhysicsPath + "\\" + file.Id + ".jpg").ReadAllBytes();

            image.Dispose();

            var manager = new FileManager(User);
            await manager.CreateAsync(file);

            return Json(true, data: new { id = file.Id, url = "data:image/jpg;base64," + Convert.ToBase64String(file.ThumbnailData), name = file.FileName, length = file.Data.Length },
                   contentType: SaleManagentConstants.Misc.JsonResponseContentType);
        }

        [HttpPost]
        public async Task<JsonResult> RemoveAttachment(string fileId)
        {
            var manager = new FileManager(User);
            var result = await manager.DeleteAsync(fileId);
            return Json(result);
        }

        public async Task<JsonResult> GetSpotGoodsPatterns(string typeId)
        {
            var manager = new SpotGoodsPatternManager(User);
            var result = await manager.GetSpotGoodsPatternListAsync(typeId);
            return Json(true, string.Empty, result);
        }
    }
}

SaleManagement.Protal/Views/SpotGoodsPattern/Add.cshtml
@model SaleManagement.Protal.Models.SpotGoodsPattern.SpotGoodsPatternEditViewModel
@{
    Layout = null;
}


@using (Html.BeginForm("Save", "SpotGoodsPattern", FormMethod.Post, new { id = "SpotGoodsPatternForm" }))
{
    @Html.HiddenFor(model => model.Id)
    <div class="form-horizontal">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">×</button>
            <h4 class="modal-title">@(string.IsNullOrEmpty(Model.Id)?"新增款式":"编辑款式")</h4>
        </div>
        <div class="modal-body">
     
            <div class="form-group">
                <label class="control-label col-md-2" for="Weight">
                    <span class="text-danger">*</span>标签
                </label>
                <div class="col-md-10">  
                  
                    <div class="col-md-10 col-xs-8" id="divSpotGoodType">
                        @foreach (var spotGoodType in Model.SpotGoodTypes)
                        {
                            var currentClass = Model.SpotGoodsPatternTypeIds!=null && Model.SpotGoodsPatternTypeIds.Any(t=> t== spotGoodType.Id) ? "btn btn-default btn-sm btn-primary" : "btn btn-sm btn-default";
                            <span class="@currentClass" data-value="@spotGoodType.Id">@spotGoodType.Name</span>
                        }
                        @Html.HiddenFor(model => model.SpotGoodsPatternTypeIdStr)
                        @Html.ValidationMessageFor(model => model.SpotGoodsPatternTypeIds, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            
            <div class="form-group" id="divCategory">
                <label class="control-label col-md-2"><span class="text-danger">*</span>品类：</label>
                <div class="col-md-10 col-xs-8" id="divProductCategory">
                    @foreach (var category in Model.ProductCategories)
                    {
                        var currentClass = category.Id == Model.ProductCategoryId ? "btn btn-default btn-sm btn-primary" : "btn btn-sm btn-default";
                        <span class="@currentClass" data-value="@category.Id">@category.Name</span>
                    }
                    @Html.HiddenFor(model => model.ProductCategoryId)
                    @Html.ValidationMessageFor(model => model.ProductCategoryId, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group" id="divGemCategory">
                <label class="control-label col-md-2"><span class="text-danger">*</span>宝石品类：</label>
                <div class="col-md-10 col-xs-8">
                    @foreach (var gemCategory in Model.GemCategories)
                    {
                        var currentClass = gemCategory.Id == Model.GemCategoryId ? "btn btn-sm btn-default btn-primary" : "btn btn-sm btn-default";
                        <span class="@currentClass" name="btnSpan" data-value="@gemCategory.Id">@gemCategory.Name</span>
                    }
                    @Html.HiddenFor(model => model.GemCategoryId)
                    @Html.ValidationMessageFor(model => model.GemCategoryId, "", new { @class = "text-danger" })
                </div>
            </div>
            
            <div class="form-group">
                <label class="control-label col-md-2" for="Weight">
                    <span class="text-danger">*</span>简介
                </label>
                <div class="col-md-6">
                    @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2" for="Weight">
                    <span class="text-danger">*</span>参考价格
                </label>
                <div class="col-md-6">
                    @Html.TextBoxFor(model => model.Price, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2" for="Weight">
                    <span class="text-danger">*</span>参考数据
                </label>
                <div class="col-md-6">
                    @Html.TextBoxFor(model => model.ReferenceData, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.ReferenceData, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2" for="Weight">
                    <span class="text-danger">*</span>排序号
                </label>
                <div class="col-md-6">
                    @Html.TextBoxFor(model => model.RowNo, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.RowNo, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-12">
                    @Html.HiddenFor(m => m.FileInfoId)
                    <div class="attachment"  data-bind="visible:showImage">
                        <ul  class="thumbnails gallery">
                            <li class="thumbnail">
                                <a class="cboxElement" href="javascript:void(0)"><img data-bind="attr:{src:imageUrl}"></a>
                                <div class="well gallery-controls">
                                    <a  href="javascript:void(0)"   data-bind="click: deleteImage"class="gallery-delete btn"><i class="glyphicon glyphicon-remove"></i></a>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-md-2"></div>
                <div class="col-md-10">
                    <a class="upload-btn btn btn-danger" href="javascript:void(0);" role="button" data-toggle="popover" data-container="body" data-placement="bottom" data-original-title="" title="">
                        提交款式图片
                        <input type="file" name="file">
                    </a>
                    <span style="color:red">最多可上传1个，每个不超过4M</span>
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <a href="#" class="btn btn-default" data-dismiss="modal">关闭</a>
            <input class="btn btn-primary" type="submit" id="saveSpotGoodPattern" value="保存" />
        </div>
    </div>
}

@Scripts.Render("~/bundles/js/jqueryval")
@Scripts.Render("~/bundles/js/ajaxForm")
@Scripts.Render("~/bundles/js/fileupload")
<script type="text/javascript">
    $(function () {
        var $from = $("#SpotGoodsPatternForm"),
            addAttachmentUrl = "/SpotGoodsPattern/AddAttachment",
            removeAttachmentUrl = "/SpotGoodsPattern/RemoveAttachment",
            $fileInfoId = $("#FileInfoId");
        $wrap = $(".attachment");
        var myViewModel = {
            imageUrl: ko.observable(""),
            showImage: ko.observable(false),
            deleteImage: function () {
                $wrap.loading();
                $.ajax({
                    url: removeAttachmentUrl,
                    type: "POST",
                    dataType: "json",
                    data: {
                        fileId: $fileInfoId.val()
                    },
                    success: function (result) {
                        $wrap.data("loading").hide();
                        if (result.succeeded) {
                            myViewModel.imageUrl("");
                            myViewModel.showImage(false);
                        } else {
                            shortTips(errorMessage(result));
                        }
                    }
                });
            }
        }; 
        ko.applyBindings(myViewModel, document.getElementById('SpotGoodsPatternForm'));
        if ($fileInfoId.val() !== "") {
            myViewModel.imageUrl("/Attachment/" + $fileInfoId.val() + "/Thumbnail");
            myViewModel.showImage(true);
        }

        $from.ajaxForm({
            success: function (result) {
                if (result.succeeded) {
                    shortTips("保存成功");
                    $("#modal").modal('hide');
                } else {
                    shortTips(errorMessage(result));
                }
            }
        });

        $(".upload-btn").fileupload({
            autoUpload: true,//是否自动上传
            url: addAttachmentUrl,
            dataType: 'json',
            formData: {},
            singleFileUploads: true,
            limitMultiFileUploads: 1,
            acceptFileTypes: /(\.|\/)(gif|jpe?g|png)$/i,
            send: function (e, data) {
                $wrap.loading();
            },
            fail: function () {
                $wrap.data("loading").hide();
            },
            add: function (e, data) {
                data.submit();
            },
            done: function () {
                $wrap.data("loading").hide();
            },
            success: function (result) {//设置文件上传完毕事件的回调函数
                if (result['succeeded']) {
                    myViewModel.imageUrl(result.data["url"]);
                    myViewModel.showImage(true);
                    $fileInfoId.val(result.data["id"])
                } else {
                    shortTips(errorMessage(result));
                }
            }
        });

        $("#saveSpotGoodPattern").click(function() {
            if ($fileInfoId.val() === "") {
                shortTips("请上传款式图片");
                return false;
            }
        });

        $("#divGemCategory span").click(function () {
            var $spanBtn = $(this); 
            $spanBtn.siblings().removeClass("btn-primary");
            $spanBtn.addClass("btn-primary");
            $spanBtn.siblings("input").val($spanBtn.attr("data-value")); 
        });

        $("#divCategory span").click(function () {
            var $spanBtn = $(this); 
            $spanBtn.siblings().removeClass("btn-primary");
            $spanBtn.addClass("btn-primary");
            $spanBtn.siblings("input").val($spanBtn.attr("data-value"));
        });

        $("#divSpotGoodType span").click(function () {
            var $spanBtn = $(this);
            debugger;
            var spotGoodTypeIds = $spanBtn.siblings("input").val().split(",").filter(item => item != '');
            var indexof = spotGoodTypeIds.indexOf($spanBtn.attr("data-value"));
            if (indexof >= 0) {
                $spanBtn.removeClass("btn-primary");
                spotGoodTypeIds.splice(indexof, 1);
            } else {
                $spanBtn.addClass("btn-primary");
                spotGoodTypeIds.push($spanBtn.attr("data-value"));
            }


            $spanBtn.siblings("input").val(spotGoodTypeIds.join(','));
        });
    })

</script>

SaleManagement.Protal/Views/SpotGoodsPattern/List.cshtml
@{
    Title("现货款式管理");
}

<div>
    <ul class="breadcrumb">
        <li>
            <a href="/home/index">首页</a>
        </li>
        <li>
            <a href="/SpotGoodsPattern/list">现货款式</a>
        </li>
    </ul>
</div>

<div class="row">
    <div class="box col-md-12">
        <div class="box-inner">
            <div class="box-header well" data-original-title="">
                <h2>款式列表</h2>
                <div class="box-icon">
                    <a id="btnAdd" class="btn">
                        <i class="glyphicon glyphicon-plus"></i>
                        新增
                    </a>
                </div>
            </div>

            <div class="box-content">
                <table class="table table-striped table-bordered bootstrap-datatable  responsive">
                    <thead>
                        <tr>
                            <th>名称</th>
                            <th>类别</th>
                            <th>操作</th>
                        </tr>
                    </thead>
                    <tbody id="tbody" data-bind="foreach:spotGoodsPatterns">
                        <tr>
                            <td data-bind="text:name"></td>
                            <td data-bind="text:typeName"></td>
                            <td>
                                <a data-bind="click:$parent.EditClick" title="编辑"><i class="glyphicon glyphicon-edit"></i>编辑</a>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="text-center"><ul id="spotGoodsPatternListPage"></ul></div>
        </div>
    </div>
    <!--/span-->
</div><!--/row-->

<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
     aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">

        </div>
    </div>
</div>
@section scripts{
    @Scripts.Render("~/bundles/js/knockout")
    @Scripts.Render("~/bundles/js/pager")
    @Scripts.Render("~/bundles/js/SpotGoodsPattern/list")
}